title: Matt Morana # your name (or website title) here
logo: "/images/mattmorana7_v2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <a href="https://www.linkedin.com/in/matthewmorana/">LinkedIn</a> 
  <br>
  <a href="https://bowen.finance/cv/" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://github.com/mattmorana7">GitHub</a>
  
theme: jekyll-theme-minimal
